import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from "next/font/google";
import "./globals.css";
import Home from './page';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ponto Go",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Home>{children}</Home>
        </AppRouterCacheProvider>
        
      </body>
    </html>
  );
}
